spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # 热部署
  devtools:
    restart:
      enabled: true  # 热部署生效
      # 设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java,src/main/resources
      # 不需实时加载
      exclude: db/** #,static/**
  # thymeleaf通用配置
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    # dev环境为false，避免修改模版重启服务器
    cache: false
    encoding: UTF-8
  # 解决返回结果中文乱码问题
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    # multipart config
    multipart:
      enabled: true
      location: /Users/wugang/code/java/elasticsearch-house/tmp/images/
      file-size-threshold: 5MB
      max-request-size: 20MB


# 拦截器配置
server:
  error:
    whitelabel:
      enabled: false  # 进入SpringBoot框架自动生成whitelabel页面
# 七牛云配置
qiniu:
  access-key: xxx
  secret-key: xxx
  bucket: newcarspicture
  cdn:
      prefix:
# 阿里云短信配置
aliyun:
  sms:
    access-key: xxx
    secret-key: xxxx
    template:
      code: xxx