spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # thymeleaf通用配置
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    # dev环境为false，避免修改模版重启服务器
    cache: false
    encoding: UTF-8